<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::insert([
            [   
                'usertype'      => 'adm',
                'firstname'     => 'Rhannel',
                'lastname'      => 'Dinlasan',
                'gender'        => 'male',
                'email'         => 'rhanneldinlasan@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Caryl Anne',
                'lastname'      => 'Elistero',
                'gender'        => 'female',
                'email'         => 'elisteriocarylanne@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'John Lloyd',
                'lastname'      => 'Delos Reyes',
                'gender'        => 'male',
                'email'         => 'delosreyesjayel@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Eugene Bragado',
                'lastname'      => 'De Ocampo',
                'gender'        => 'female',
                'email'         => 'eugene@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Casey Rose',
                'lastname'      => 'De Castro',
                'gender'        => 'female',
                'email'         => 'casey@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Junnel',
                'lastname'      => 'Ramirez',
                'gender'        => 'male',
                'email'         => 'junnel@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Ma. Vanessa',
                'lastname'      => 'Bencang',
                'gender'        => 'female',
                'email'         => 'vanessa@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Hazel',
                'lastname'      => 'Gonzales',
                'gender'        => 'female',
                'email'         => 'hazel@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Mark Joseph',
                'lastname'      => 'Caisip',
                'gender'        => 'male',
                'email'         => 'joseph@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Ronniel',
                'lastname'      => 'Buhay',
                'gender'        => 'male',
                'email'         => 'ronniel@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Rizzalyn',
                'lastname'      => 'Ramirez',
                'gender'        => 'female',
                'email'         => '@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Alzeo',
                'lastname'      => 'landicho',
                'gender'        => 'male',
                'email'         => 'alzeo@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Alvin',
                'lastname'      => 'Dalida',
                'gender'        => 'male',
                'email'         => 'alvin@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Ian Glenn',
                'lastname'      => 'Mercado',
                'gender'        => 'male',
                'email'         => 'ianglenn@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'John Alex',
                'lastname'      => 'Binuya',
                'gender'        => 'male',
                'email'         => 'johnalex@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Ronel',
                'lastname'      => 'Ilao',
                'gender'        => 'male',
                'email'         => 'ronel@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'April Rose',
                'lastname'      => 'Catena',
                'gender'        => 'male',
                'email'         => 'aprilrose@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Jaypee',
                'lastname'      => 'Venzon',
                'gender'        => 'male',
                'email'         => 'jaypee@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Donnalyn',
                'lastname'      => 'Cerilo',
                'gender'        => 'female',
                'email'         => 'donnalyn@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Nel',
                'lastname'      => 'Tolentino',
                'gender'        => 'male',
                'email'         => 'nel@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'John Raven',
                'lastname'      => 'Balbar',
                'gender'        => 'male',
                'email'         => 'raven@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Jonvic',
                'lastname'      => 'samonteza',
                'gender'        => 'male',
                'email'         => 'jonvic@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Doris',
                'lastname'      => 'Carig',
                'gender'        => 'female',
                'email'         => 'doris@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Analy',
                'lastname'      => 'Dalida',
                'gender'        => 'female',
                'email'         => 'analy@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Gabriel',
                'lastname'      => 'Daluz',
                'gender'        => 'male',
                'email'         => 'gabriel@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Robert',
                'lastname'      => 'Dinlasan',
                'gender'        => 'male',
                'email'         => 'robert@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Ryan',
                'lastname'      => 'De Luna',
                'gender'        => 'male',
                'email'         => 'ryan@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Nikki Sofia',
                'lastname'      => 'Mailig',
                'gender'        => 'female',
                'email'         => 'nikki@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'emp',
                'firstname'     => 'Loren',
                'lastname'      => 'Catapang',
                'gender'        => 'female',
                'email'         => 'loren@gmail.com',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            // [   
            //     'usertype'      => 'emp',
            //     'firstname'     => 'Jhanzen',
            //     'lastname'      => 'Lopez',
            //     'gender'        => 'male',
            //     'email'         => 'jhanzen@gmail.com',
            //     'password'      => Hash::make('123123123'),
            //     'created_at'    => Carbon::now(),
            //     'updated_at'    => Carbon::now(),
            // ],
            // [   
            //     'usertype'      => 'emp',
            //     'firstname'     => 'Judith',
            //     'lastname'      => 'Manalo',
            //     'gender'        => 'female',
            //     'email'         => 'judith@gmail.com',
            //     'password'      => Hash::make('123123123'),
            //     'created_at'    => Carbon::now(),
            //     'updated_at'    => Carbon::now(),
            // ],
            // [   
            //     'usertype'      => 'emp',
            //     'firstname'     => '',
            //     'lastname'      => '',
            //     'gender'        => 'male',
            //     'email'         => '@gmail.com',
            //     'password'      => Hash::make('123123123'),
            //     'created_at'    => Carbon::now(),
            //     'updated_at'    => Carbon::now(),
            // ],
        ]);
    }
}
